# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02c3116965a7b8a56f0a8ae97711226b7d50a184a466b9f9a90042a35f0d54f83d21de2010b1f23e82b0ada280cbd7aa57f253622960c6281848d1d31babe046

test:
  secret_key_base: 438c0952d6e1459f430cdceff42cf8bb3405e828b2815cf76511f415ea3b04929b7e78ba1f8e3d6935f40d9a4180ab8c9b71b36e7e6c34806a8a0c54f3d69407

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
